wallpaper {
    monitor = DP-4
    path = ~/Pictures/wallpapers/fu5v0xm7ym6e1_2.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/Pictures/wallpapers/fu5v0xm7ym6e1_2.png
    fit_mode = cover
}